<a href="https://colab.research.google.com/github/2303A51876/BT-14_1876_Python-for-DS/blob/main/LAB-3%20ASSIGNMENTS.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
#LAB-3 ASSIGNMENT-1
#Q1: Matrix Addition and Subtraction
import numpy as np

# Create random 3x3 matrices
A = np.random.randint(1, 10, (3, 3))
B = np.random.randint(1, 10, (3, 3))

print("Matrix A:\n", A)
print("Matrix B:\n", B)

# Addition & Subtraction
print("\nA + B:\n", np.add(A, B))
print("\nA - B:\n", np.subtract(A, B))


Matrix A:
 [[3 2 1]
 [6 2 7]
 [7 8 9]]
Matrix B:
 [[1 4 3]
 [8 4 6]
 [4 9 2]]

A + B:
 [[ 4  6  4]
 [14  6 13]
 [11 17 11]]

A - B:
 [[ 2 -2 -2]
 [-2 -2  1]
 [ 3 -1  7]]


In [3]:
#LAB-3 ASSIGNMENT-2
#Q2: 2D Matrix Multiplication (Dot Product)
# Create 3x2 and 2x3 matrices
X = np.array([[1, 2], [3, 4], [5, 6]])
Y = np.array([[7, 8, 9], [10, 11, 12]])

print("Matrix X:\n", X)
print("Matrix Y:\n", Y)

# Dot product
result = np.dot(X, Y)
print("\nDot Product Result:\n", result)


Matrix X:
 [[1 2]
 [3 4]
 [5 6]]
Matrix Y:
 [[ 7  8  9]
 [10 11 12]]

Dot Product Result:
 [[ 27  30  33]
 [ 61  68  75]
 [ 95 106 117]]
