<a href="https://colab.research.google.com/github/2303A51876/BT-14_1876_Python-for-DS/blob/main/LAB-2%20ASSIGNMENTS.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
#LAB-2 ASSIGNMENT-1
#Q1: Student Grades Analysis Using NumPy
import numpy as np

# Create 2D array (5 students × 3 subjects)
marks = np.array([
    [85, 78, 92],
    [60, 70, 65],
    [90, 95, 88],
    [72, 68, 74],
    [88, 82, 80]
])

print("Student Marks:\n", marks)

# Average, min, max
print("\nAverage marks:", np.mean(marks))
print("Minimum mark:", np.min(marks))
print("Maximum mark:", np.max(marks))

# Marks of specific student (3rd student)
print("\n3rd Student Marks:", marks[2])

# Students scoring above 80 in any subject
print("\nStudents scoring > 80:\n", marks[marks > 80])

# Reshape to subject-wise (3 subjects × 5 students)
reshaped = marks.reshape(3, 5)
print("\nReshaped (Subjects × Students):\n", reshaped)


Student Marks:
 [[85 78 92]
 [60 70 65]
 [90 95 88]
 [72 68 74]
 [88 82 80]]

Average marks: 79.13333333333334
Minimum mark: 60
Maximum mark: 95

3rd Student Marks: [90 95 88]

Students scoring > 80:
 [85 92 90 95 88 88 82]

Reshaped (Subjects × Students):
 [[85 78 92 60 70]
 [65 90 95 88 72]
 [68 74 88 82 80]]


In [1]:
#LAB-2 ASSIGNMENT-2
#Q2: Employee Salary Analysis with pandas
import pandas as pd

# Create DataFrame
data = {
    "ID": [101, 102, 103, 104, 105],
    "Name": ["Alice", "Bob", "Charlie", "David", "Eva"],
    "Department": ["HR", "IT", "Finance", "IT", "HR"],
    "Salary": [45000, 60000, 75000, 50000, 90000]
}
df = pd.DataFrame(data)
print("Original Data:\n", df)

# Filter salary > 50000
print("\nEmployees with salary > 50000:\n", df[df["Salary"] > 50000])

# Sort by salary (descending)
print("\nSorted by Salary:\n", df.sort_values(by="Salary", ascending=False))

# Add Bonus (10% of salary)
df["Bonus"] = df["Salary"] * 0.10
print("\nWith Bonus:\n", df)

# Total expense
df["Total"] = df["Salary"] + df["Bonus"]
print("\nTotal Salary Expense:", df["Total"].sum())


Original Data:
     ID     Name Department  Salary
0  101    Alice         HR   45000
1  102      Bob         IT   60000
2  103  Charlie    Finance   75000
3  104    David         IT   50000
4  105      Eva         HR   90000

Employees with salary > 50000:
     ID     Name Department  Salary
1  102      Bob         IT   60000
2  103  Charlie    Finance   75000
4  105      Eva         HR   90000

Sorted by Salary:
     ID     Name Department  Salary
4  105      Eva         HR   90000
2  103  Charlie    Finance   75000
1  102      Bob         IT   60000
3  104    David         IT   50000
0  101    Alice         HR   45000

With Bonus:
     ID     Name Department  Salary   Bonus
0  101    Alice         HR   45000  4500.0
1  102      Bob         IT   60000  6000.0
2  103  Charlie    Finance   75000  7500.0
3  104    David         IT   50000  5000.0
4  105      Eva         HR   90000  9000.0

Total Salary Expense: 352000.0
